---
title: "Hypothesis 3 (PROLIFIC)"
author: "Katie Warburton"
format: html
editor: visual
---

### Imports

```{r message=FALSE, warning=FALSE, results='hide'}
library(stringr) 
library(tidyverse) 
library(dplyr) 
library(lme4) 
library(ggplot2) 
library(lmtest) 
library(brms) 
library(tidybayes) 
library(parameters) 

set.seed(13)
```

### Data

```{r}
df <- read.csv('Results/level2_trial_data.csv',  na.strings=c("","NA"))  
df$DEPTH <- relevel(factor(df$DEPTH), ref='3')
df$HAS_X <- as.numeric(df$NUM_X > 0)
```

### Hypothesis

Depth has an effect such that a new category (X) will appear more often in the 2-level than in the 3-level condition.

### Frequentist

```{r}
m1 <- glmer(HAS_X ~ 1 + DEPTH + (1|P_ID) + (1|STIMULI),
            family = binomial,
            data = df)

m1.1 <- glmer(HAS_X ~ 1 + DEPTH + POOL + (1|P_ID) + (1|STIMULI),
            family = binomial,
            data = df)
lrtest(m1, m1.1)


m1.2 <- glmer(HAS_X ~ 1 + DEPTH + (1|POOL/P_ID) + (1|STIMULI),
            family = binomial,
            data = df)

lrtest(m1, m1.2)

```

```{r}
m0 <- glmer(HAS_X ~ 1 + (1|P_ID)  + (1|STIMULI),
            family = binomial,
            data = df)
lrtest(m0, m1)
fixef(m1)
```
